name: Node CI

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: install
        run: yarn
        env:
          CI: true

      - name: Test
        run: yarn lerna run test

      - name: Build
        run: yarn lerna run build

      - name: Release
        run: yarn lerna version from package